### ISSUE TITLE
got a warning, is it harmless?

### ISSUE THREAD

**Issue by saurabh-kataria** [AGI-Arena/MARS#1]
Thanks for your work. MARS is working wonderfully well on a range of architectures in my personal projects. I just wanted to make sure I am not missing out on more benefits 😁

> ./MARS/MARS/optimizers/mars.py:23: UserWarning: This overload of add_ is deprecated:
>         add_(Number alpha, Tensor other)
> Consider using one of the following signatures instead:
>         add_(Tensor other, *, Number alpha = 1) (Triggered internally at /opt/conda/conda-bld/pytorch_1729647348947/work/torch/csrc/utils/python_arg_parser.cpp:1642.)
>   exp_avg.mul_(beta1).add_(1. - beta1, c_t)

**Comment by lauyikfung** [comment]
Thank you for your notice. It is just because we used the old version of usage of "add_" function, and the warning does not affect the performance. To avoid the warning, we have updated the optimizer file. :)
